working parallel processing w/ multithreaded tess

diff --git a/readablepdf b/readablepdf
--- a/readablepdf
+++ b/readablepdf
@@ -362,16 +362,20 @@ done
 echo "Estimating CPU-Threads"
 # Estimate CPU Cores (see pdfsandwich code for reference)
 CPU_THREADS=$(cat /proc/cpuinfo | grep processor | awk '{a++} END {print a}')
-export OMP_THREAD_LIMIT=$CPU_THREADS
+OMP_THREAD_LIMIT=$CPU_THREADS
+MAX_JOBS=$(expr $CPU_THREADS / 4)
+# tesseract only uses 4 threads
 
 echo "Using up to $CPU_THREADS threads."
-echo "Running tesseract-ocr"
 
-# if command -v parallel >/dev/null; then
-#	parallel tesseract "{}" "{.}" "${TESSERACT_PARAMS}" hocr ::: *.tif
-# else
-for i in ./*.tif; do tesseract $i $(basename "$i") ${TESSERACT_PARAMS} hocr; done;
-# fi
+# command -v foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's not installed.  Aborting."; exit 1; }
+
+if command -v parallel >/dev/null; then
+	parallel -P ${MAX_JOBS} tesseract "{}" "{.}" "${TESSERACT_PARAMS}" hocr ::: *.tif
+ else
+	 for i in ./*.tif; do tesseract $i $(basename "$i") ${TESSERACT_PARAMS} hocr; done;
+fi
+
 
 
 # pdfbeads doesn't play nice with filenames with spaces. There's nothing we can do
