Added parameters, config file, and some minor code improvements.

diff --git a/readablepdf b/readablepdf
--- a/readablepdf
+++ b/readablepdf
@@ -1,11 +1,20 @@
 #!/bin/bash
 # readablepdf
+#
 # ReadablePDF streamlines the effort of turning a not so great PDF into
 # a more easily readable PDF (or of course a pretty decent PDF into an
-# even better one). This script depends on poppler-utils, imagemagick,
-# scantailor, tesseract-ocr, jbic2enc, and pdfbeads.
+# even better one). Copyright (C) 2014 Frans de Jonge.
 #
-# Unfortunately only the first four are available in the Debian repositories.
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 3 of the License, or
+# (at your option) any later version.
+#
+##############################################
+#
+# This script depends on poppler-utils, imagemagick, scantailor,
+# tesseract-ocr, jbic2enc, and pdfbeads. Unfortunately only the first four
+# are available in the Debian repositories.
 # sudo apt install poppler-utils imagemagick scantailor tesseract-ocr
 #
 # For more background information and how to install jbig2enc and pdfbeads,
@@ -16,7 +25,215 @@
 #
 # Aspell dictionaries tend to be called things like aspell-en, aspell-nl, etc.
 
-BASENAME=${@%.pdf} # or `basename "@%" .pdf`
+## Version info
+version=0.9
+version_info=$'readablepdf '${version}$'
+Copyright (C) 2014 Frans de Jonge.
+
+This program is free software; you can redistribute it and/or modify
+it under the terms of the GNU General Public License as published by
+the Free Software Foundation; either version 3 of the License, or
+(at your option) any later version.'
+
+## Helper functions and variables for command line switches.
+dependencies=$'This script depends on poppler-utils, imagemagick, scantailor,
+tesseract-ocr, jbic2enc, and pdfbeads. Unfortunately only the first four
+are available in the Debian repositories.
+sudo apt install poppler-utils imagemagick scantailor tesseract-ocr
+
+For more background information and how to install jbig2enc and pdfbeads,
+see http://fransdejonge.com/2014/10/fixing-up-scanned-pdfs-with-scan-tailor#harder-post-processing
+
+GNU Aspell and GNU Parallel are recommended but not required.
+sudo apt install aspell parallel
+
+Aspell dictionaries tend to be called things like aspell-en, aspell-nl, etc.'
+usage="Usage: $0 [-a] [-r <0|90|180|270>] [FILE.pdf]"
+help=$usage'
+
+ReadablePDF streamlines the effort of turning a not so great PDF into
+a more easily readable PDF (or of course a pretty decent PDF into an
+even better one).
+
+Image-processing:
+  -a, --auto-rotate       Automatically try to determine rotation and act accordingly.
+  -r, --rotate            A number of degrees by which to rotate. Typically 90, 180 or 270.
+  -l, --language          The language for OCR. See '"'tesseract --list-langs'"$' for available
+                          languages. Combine languages like eng+nld.
+  -t, --tesseract-params  Parameters to pass to Tesseract.
+
+Miscellaneous
+  -v, --version           Display version information.
+
+Configuration file:
+A system-wide configuration file can be created in /etc/readablepdf.conf
+and a user configuration file can be created in ~/.config/readablepdf.conf.
+
+A configuration file might look like follows. Values are enclosed within
+single quotation marks:
+
+# Always enable auto-rotate
+AUTO_ROTATE='"'true'"$'
+# Set default language to English + Dutch
+TESSERACT_LANGUAGE='"'eng+nld'"$'
+
+'$dependencies
+
+echo_error() {
+	echo "Error: $1"
+	echo
+	echo_usage
+}
+
+echo_help() {
+	echo "${help}"
+	exit 1
+}
+
+echo_usage() {
+	echo "${usage}"
+	echo "Try '$0 --help' for more information."
+	exit 1
+}
+
+echo_version() {
+	echo "${version_info}"
+	exit 1
+}
+
+## Declare variables that might change through config file or command line switches.
+AUTO_ROTATE=false
+ROTATE=0
+TESSERACT_LANG="eng"
+#TESSERACT_PARAMS=${TESSERACT_LANG}
+TESSERACT_PARAMS=
+
+## Change variables through config file
+# Inspired by http://wiki.bash-hackers.org/howto/conffile
+# Both system-wide and per user conf; something along these lines.
+load_config() {
+# Paranoid whitelist.
+unknown=$(< "$1" grep -Evi "^(#.*|[A-Z_]*='[a-z0-9 +-]*')$")
+if [ -n "${unknown}" ]; then
+ echo "Error in config file. Disallowed lines:"
+ echo "${unknown}"
+ exit 1
+fi
+source "$1"
+}
+
+c_files=( "/etc/readablepdf.cfg" "${HOME}/.config/readablepdf.conf" )
+
+for c_file in "${c_files[@]}"; do
+	if [ -r "$c_file" ]; then
+		load_config "$c_file"
+	fi
+done
+
+## Process flags
+# Thanks to http://stackoverflow.com/a/9899366
+# This shows how to handle combined short options along with
+# other long and short options. It does so by splitting them
+# apart (e.g. 'tar -xvzf ...' -> 'tar -x -v -z -f ...')
+
+while test $# -gt 0
+do
+	case $1 in
+
+	# Normal option processing
+		-h | --help)
+			# usage and help
+			echo_help
+			;;
+		-v | --version)
+			# version info
+			echo_version
+			;;
+		-l | --language)
+			# Perform a simple syntax check at the very beginning.
+			if [[ "$2" =~ ^[a-z]{3}([+]?[a-z]{3}){0,}$ ]]; then
+				TESSERACT_LANG=$2
+				shift
+			else
+				echo_error "$1 needs a valid lower case three-character language string. Combine languages like 'eng+nld'."
+			fi
+			;;
+		--tesseract-params)
+			if [ -z "$2" ]; then
+				echo_error "$1 requires parameters for Tesseract. See 'tesseract --help' for more information."
+				echo_usage
+			else
+				TESSERACT_PARAMS=$2
+				shift
+			fi
+			;;
+		-r | --rotate)
+			case $2 in
+				''|*[!0-9-.]*)
+					# Not a number.
+					echo_error "$1 needs a number of degrees."
+					;;
+				*)
+					# It's a number.
+					ROTATE=$2
+					shift
+					;;
+			esac
+			;;
+		-a | --auto-rotate)
+			AUTO_ROTATE=true
+			;;
+	# ...
+
+	# Special cases
+		--)
+			break
+			;;
+		--*)
+			# error unknown (long) option $1
+			echo_error "unknown (long) option $1"
+			;;
+		-?)
+			# error unknown (short) option $1
+			echo_error "unknown (short) option $1"
+			;;
+
+	# FUN STUFF HERE:
+	# Split apart combined short options
+		-*)
+			split=$1
+			shift
+			set -- "$(echo "$split" | cut -c 2- | sed 's/./-& /g')" "$@"
+			continue
+			;;
+
+	# Done with options
+		*)
+			break
+			;;
+	esac
+
+	# for testing purposes:
+	echo "testing $1"
+
+	shift
+done
+
+# Check that rotate and automatic-rotate aren't given together?
+
+# Add -l option to parameters if there's no conflict.
+if [[ "${TESSERACT_PARAMS}" != *-l* ]]; then
+	TESSERACT_PARAMS="-l ${TESSERACT_LANG} ${TESSERACT_PARAMS}"
+fi
+
+# If no file given, display usage info.
+#if [ -z "$1" ] || [ -z "${p}" ]; then
+if [ -z "$1" ]; then
+	echo_error "Specify a file to process."
+	echo_usage
+fi
+
+BASENAME=${*%.pdf}
 
 # It would seem that at some point in its internal processing, pdfbeads has issues with spaces.
 # Let's strip them and perhaps some other special characters so as still to provide
@@ -28,8 +245,6 @@ BASENAME_SAFE=$(echo "${BASENAME_SAFE}" | tr -d ".()\"'") # Get rid of all perio
 SCRIPTNAME=$(basename "$0" .sh)
 TMP_DIR=${SCRIPTNAME}-${BASENAME_SAFE}
 
-TESSERACT_PARAMS="-l eng+nld"
-
 
 # If project file exists, change directory and assume everything's in order.
 # Else do the preprocessing and initiation of a new project.
@@ -40,7 +255,9 @@ else
 	echo "File ${TMP_DIR}/${BASENAME_SAFE}.ScanTailor does not exist."
 	
 	# Let's get started.
-	mkdir "${TMP_DIR}"
+	if [ ! -d "${TMP_DIR}" ]; then
+		mkdir "${TMP_DIR}"
+	fi
 	cd "${TMP_DIR}"
 	
 	# Only output PNG to prevent any potential further quality loss.
@@ -52,73 +269,75 @@ else
 	DPI=$(pdfimages -list "../${BASENAME}.pdf" | sed -n 3p | awk '{print $13}')
 	
 #<<'end_long_comment'
-	# TODO Skip all this based on a rotation command-line flag!
-	# Adapted from http://stackoverflow.com/a/9778277
-	# Scan Tailor says it can't automatically figure out the rotation.
-	# I'm not a programmer, but I think I can do well enough by (ab)using OCR. :)
-	file="${BASENAME_SAFE}-000.png"
-	
-	TMP="/tmp/${TMP_DIR}-rotation-calc"
-	mkdir ${TMP}
+	if [ "${AUTO_ROTATE}" = true ]; then
+		# TODO Skip all this based on a rotation command-line flag!
+		# Adapted from http://stackoverflow.com/a/9778277
+		# Scan Tailor says it can't automatically figure out the rotation.
+		# I'm not a programmer, but I think I can do well enough by (ab)using OCR. :)
+		file="${BASENAME_SAFE}-000.png"
 
-	# Make copies in all four orientations (the src file is 0; copy it to make 
-	# things less confusing)
-	north_file="${TMP}/0"
-	east_file="${TMP}/90"
-	south_file="${TMP}/180"
-	west_file="${TMP}/270"
+		TMP="/tmp/${TMP_DIR}-rotation-calc"
+		mkdir "${TMP}"
 
-	cp "$file" "$north_file"
-	convert -rotate 90 "$file" "$east_file"
-	convert -rotate 180 "$file" "$south_file"
-	convert -rotate 270 "$file" "$west_file"
+		# Make copies in all four orientations (the src file is 0; copy it to make
+		# things less confusing)
+		north_file="${TMP}/0"
+		east_file="${TMP}/90"
+		south_file="${TMP}/180"
+		west_file="${TMP}/270"
 
-	# OCR each (just append ".txt" to the path/name of the image)
-	north_text="$north_file.txt"
-	east_text="$east_file.txt"
-	south_text="$south_file.txt"
-	west_text="$west_file.txt"
+		cp "$file" "$north_file"
+		convert -rotate 90 "$file" "$east_file"
+		convert -rotate 180 "$file" "$south_file"
+		convert -rotate 270 "$file" "$west_file"
 
-	# tesseract appends .txt automatically
-	tesseract "$north_file" "$north_file"
-	tesseract "$east_file" "$east_file"
-	tesseract "$south_file" "$south_file"
-	tesseract "$west_file" "$west_file"
+		# OCR each (just append ".txt" to the path/name of the image)
+		north_text="$north_file.txt"
+		east_text="$east_file.txt"
+		south_text="$south_file.txt"
+		west_text="$west_file.txt"
 
-	# Get the word count for each txt file (least 'words' == least whitespace junk
-	# resulting from vertical lines of text that should be horizontal.)
-	wc_table="$TMP/wc_table"
-	echo "$(wc -w ${north_text}) ${north_file}" > $wc_table
-	echo "$(wc -w ${east_text}) ${east_file}" >> $wc_table
-	echo "$(wc -w ${south_text}) ${south_file}" >> $wc_table
-	echo "$(wc -w ${west_text}) ${west_file}" >> $wc_table
+		# tesseract appends .txt automatically
+		tesseract "$north_file" "$north_file"
+		tesseract "$east_file" "$east_file"
+		tesseract "$south_file" "$south_file"
+		tesseract "$west_file" "$west_file"
 
-	# Spellcheck. The lowest number of misspelled words is most likely the 
-	# correct orientation.
-	misspelled_words_table="$TMP/misspelled_words_table"
-	while read record; do
-		txt=$(echo "$record" | awk '{ print $2 }')
-		# This is harder to automate away, pretend we only deal with English and Dutch for now.
-		misspelled_word_count=$(< "${txt}" aspell -l en list | aspell -l nl list | wc -w)
-		echo "$misspelled_word_count $record" >> $misspelled_words_table
-	done < $wc_table
+		# Get the word count for each txt file (least 'words' == least whitespace junk
+		# resulting from vertical lines of text that should be horizontal.)
+		wc_table="$TMP/wc_table"
+		echo "$(wc -w ${north_text}) ${north_file}" > $wc_table
+		echo "$(wc -w ${east_text}) ${east_file}" >> $wc_table
+		echo "$(wc -w ${south_text}) ${south_file}" >> $wc_table
+		echo "$(wc -w ${west_text}) ${west_file}" >> $wc_table
 
-	# Do the sort, overwrite the input file, save out the text
-	winner=$(sort -n $misspelled_words_table | head -1)
-	rotated_file=$(echo "${winner}" | awk '{ print $4 }')
-	
-	rotation=$(basename "${rotated_file}")
-	
-	echo "Rotating ${rotation} degrees"
+		# Spellcheck. The lowest number of misspelled words is most likely the 
+		# correct orientation.
+		misspelled_words_table="$TMP/misspelled_words_table"
+		while read record; do
+			txt=$(echo "$record" | awk '{ print $2 }')
+			# This is harder to automate away, pretend we only deal with English and Dutch for now.
+			misspelled_word_count=$(< "${txt}" aspell -l en list | aspell -l nl list | wc -w)
+			echo "$misspelled_word_count $record" >> $misspelled_words_table
+		done < $wc_table
 
-	# Clean up.
-	if [ -d ${TMP} ]; then
-		rm -r ${TMP}
+		# Do the sort, overwrite the input file, save out the text
+		winner=$(sort -n $misspelled_words_table | head -1)
+		rotated_file=$(echo "${winner}" | awk '{ print $4 }')
+
+		ROTATE=$(basename "${rotated_file}")
+
+		echo "Auto-rotating ${ROTATE} degrees"
+
+		# Clean up.
+		if [ -d "${TMP}" ]; then
+			rm -r "${TMP}"
+		fi
+		# TODO end skip
 	fi
-	# TODO end skip
 	
-	if [[ ${rotation} -ne 0 ]]; then
-		mogrify -rotate "${rotation}" "${BASENAME_SAFE}-*.png"
+	if [[ ${ROTATE} -ne 0 ]]; then
+		mogrify -rotate "${ROTATE}" "${BASENAME_SAFE}-*.png"
 	fi
 #end_long_comment
 	
@@ -137,9 +356,9 @@ done
 
 # Use GNU Parallel to speed things up if it exists.
 if command -v parallel >/dev/null; then
-	parallel tesseract {} {.} ${TESSERACT_PARAMS} hocr ::: *.tif
+	parallel tesseract "{}" "{.}" "${TESSERACT_PARAMS}" hocr ::: *.tif
 else
-	for i in ./*.tif; do tesseract $i $(basename $i) ${TESSERACT_PARAMS} hocr; done;
+	for i in ./*.tif; do tesseract "$i" "$(basename "$i")" "${TESSERACT_PARAMS}" hocr; done;
 fi
 
 # pdfbeads doesn't play nice with filenames with spaces. There's nothing we can do
